version: '2'
services: 

  eventposter:
    build: ./eventposter
    volumes: 
        - ./eventposter:/github.com/mramshaw/go-docker-eventstore/poster
    links:
      - eventstore
  eventstore:
    build: ./eventstore
    ports:  
      - "2113:2113"
      - "1113:1113"
